### PR TITLE
Allow custom metadata and schema

### LINKED ISSUE #63: generate tables on custom metadata
I'm loving aldjemy, and I came up with a new interesting use case. I'm using PostgreSQL foreign data wrappers to copy loads of data from one django instance to another. To do this transfer, I need to copy between tables in different schemas. I can write these queries using SQLAlchemy, so that's what I want to do.

To that end, I want to make a custom schema, and then run `aldjemy.core.prepare_models` on it. Unfortunately, Aldjemy is pretty deeply tied to it's internal cache of the default, schema-free metadata.

I've figured out the changes needed for this, and I am using this code and it seems to be working. Since Django doesn't usually ever deal with schemas, a multiple-schema use-case, I wasn't sure if making Aldjemy internals more amenable to my use case would be something you'd be interested in having me contribute. If it would, I'd be happy to do just that. I've already got it working, I'd just need to work it into a pull request.

There are three functions that I've found need to be touched:

* `aldjemy.core.prepare_models` needs to allow passing in a custom metadata instance, and using that to do the generation.
* `aldjemy.table.generate_tables` needs to handle the case of the metadata having a schema when checking if the table exists.
*  `aldjemy.orm._extract_model_attrs` needs to support passing in a custom metadata, using that to get the tables, and use the metadata's schema when looking up the table.

All in all, pretty minor changes, but I'm not sure if cleaning things up to make that easy for me is something you think would be worthwhile to entertain a pull request for.

### PR DESCRIPTION
**Pull request by ryanhiebert**
A PR to fix #63 as I promised.

### CODE REVIEW

**Comment by Deepwalker** [comment]
Hi, can we add some tests for new behaviour?

**Comment by Deepwalker** [comment]
Changes looks good to me, will be happy to merge them BTW

**Comment by ryanhiebert** [comment]
Cool, can do. I removed `get_tables` because it seemed better to just pull the tables off of the metadata, and since no tests broke, that seemed OK to me. But I wanted to call it out to make sure you noticed that change.

I'll be happy to write up some tests when I get a free moment. Not sure how quickly that will happen, might be next week.

And if you're interested in having me on as a maintainer, I'd be happy to help out with that. I personally usually wait until I've gotten a full solid contribution from somebody before I add them as a maintainer, and I'm not pushing you for it either now or later, but I wanted to make myself available if you'd like that.

**Comment by ryanhiebert** [comment]
OK, here we go. I fixed a bug, simplified the API to return only a single value, and added the test you asked for. Thanks for being willing to entertain this idea!

**Comment by ryanhiebert** [comment]
@Deepwalker : Thank you for merging this. What are you thinking about when you want to cut a new release?

**Comment by ryanhiebert** [comment]
@Deepwalker : you've been very quick to respond and merge this through this process (thank you very much), so I wanted to make sure my question wasn't accidentally missed. Do you have other items that you want completed before making a new release of aldjemy? When are you thinking you might be able to cut a new release?

**Comment by Deepwalker** [comment]
Sorry, I'm bit busy this week. Released it, check 0.9.0

**Comment by ryanhiebert** [comment]
Awesome, thank you very much. I totally understand getting busy.

**Comment by ryanhiebert** [comment]
I'm still tracking down the cause, but there is an issue with this release that is not allowing it to load models in my project after upgrading.

**Pull request merged**
