### PR TITLE
Add aldjemy.meta.AldjemyMeta for easier mixins

### PR DESCRIPTION
**Pull request by akheron**
Using this metaclass, all callables and properties get exposed
automatically and you don't need to create a separate mixin class.

### CODE REVIEW

**Comment by akheron** [comment]
I'm not sure whether this is the "most correct" way to do it, but at least it works. The metaclass dynamically creates the mixin class and assings it to the model's `aldjemy_mixin`  class variable.

Also, I don't have a Python 2 project handy right now, so I haven't tested this with Python 2. But I don't see why this wouldn't work with Python 2 out of the box.

**Comment by Deepwalker** [comment]
It does not broke anything, so why not?

**Comment by luzfcb** [comment]
Sounds good, but there is no test for this patch?!

This works with multiple inheritance of django?

Taking advantage of the issue, have you seen the django team wants to integrate SQLAlchemy into django: 
https://code.djangoproject.com/wiki/SummerOfCode2015#SQLAlchemyNoSQLintegration

this project seems a good start. :-)

**Comment by Deepwalker** [comment]
It is rare to see tests in pull requests.
I think this project is completely unrelated to django plans - they want to connect sqla models to admin site.

**Comment by luzfcb** [comment]
ok, the link is very specific, but is consensus (of the core developers django) that this link is only a short guide for those who are no ideas, nobody is obliged to follow the guide. 

I think the work you have done here at least should be submitted to django core developers so they at least know that it exists.

It is a good project for Google Summer of Code.

anyway, thanks for the hard work.

**Pull request merged**
