### PR TITLE
Ignore missing columns

### LINKED ISSUE #65: 0.8 broken for me
Using an editable install to a local repository, and git bisect, I've determined that the error is caused by the commit from #59. I don't have the solution worked out yet, but I wanted to inform about the issue I'm seeing, and what I've been able to determine about it so far. I'm not sure how many other people might be seeing this issue, I've only tested it on my own private codebase.

```
Traceback (most recent call last):
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/bin/django", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django_cmd.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ryan/Code/aspiredu/aspiredu/aspiredu/project/__init__.py", line 1, in <module>
    from .celery import app
  File "/home/ryan/Code/aspiredu/aspiredu/aspiredu/project/celery.py", line 50, in <module>
    django.setup()
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/ryan/Code/python/aldjemy/aldjemy/apps.py", line 17, in ready
    prepare_models()
  File "/home/ryan/Code/python/aldjemy/aldjemy/orm.py", line 145, in prepare_models
    attrs = _extract_model_attrs(model, sa_models_by_django_models)
  File "/home/ryan/Code/python/aldjemy/aldjemy/orm.py", line 53, in _extract_model_attrs
    attrs[f.name] = orm.column_property(table.c[f.column])
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: 'data'
```

### PR DESCRIPTION
**Pull request by ryanhiebert**
I'm not sure exactly why my field isn't in the columns it's looking up, but it's a `django.contrib.postgres.fields.JSONField`, and it likely has something to do with that. Anyway, just checking to ensure it is indeed in the dict of columns is good enough to solve the issue for me.

Fixes #65

### CODE REVIEW

**Comment by Deepwalker** [comment]
What is a reason for this error? Can we adjust tests that they will fail for this case?

**Comment by ryanhiebert** [comment]
I still don't know the cause of this error, I just know that it's a regression. I've added a test in the postgresql suite, and that a) failed before the fix, and b) passed after the fix. I did note that the tests on Circle don't run those tests, but that's not new to this issue, so I'm not inclined to think that should hold up merging this.

**Comment by ryanhiebert** [comment]
@Deepwalker : is there anything else you're wanting me to do with this PR before merge?

**Comment by ryanhiebert** [comment]
Thanks for merging it, @Deepwalker. Think you could cut a release with this regression fix?

**Comment by Deepwalker** [comment]
Released 0.9.1. About next releases I not sure what to do. Do not use it in my current projects, so do not work with it and do not develop it.  In current state I can guarantee that I will at least review PRs.

I think you can create your fork and if it will be successful people will vote with stars and downloads. And I will be free )

**Comment by ryanhiebert** [comment]
Thanks for the release. I'm not inclined toward a fork unless you're wanting to step away and would like to give me ownership of the repo and the PyPI name. That's fine if you really would like to step away, but I'm also good with you being the one to cut releases and keep the name recognition. Add me as a collaborator, and I'll be happy to merge PRs. I've really be helped by this library, so I'm happy to help maintain it.

If I were you, I'd probably make me a collaborator, perhaps a maintainer on PyPI, but I probably wouldn't surrender the repo to me just yet. Let me prove myself a bit more, and that you're happy with the decisions I make. If you'd rather just be done with it, I'm willing to take it over entirely if you prefer.

**Pull request merged**
